README.md

Without this, the `ark send --to ...` command later in the tutorial fails because it can't read password from STDIN.

fix: add -it flag to ark alias in README

---

server/.gitignore
server/internal/infrastructure/db/badger/vtxo_repo.go

This PR removes the reset statement on expireAt member. Thus, a swept Vtxo will keep its `expireAt` timestamp value.
it closes #170 
@bordalix @tiero please review

do not set expireAt=0 when vtxo is swept

---

server/internal/core/application/service.go
server/internal/core/domain/round_repo.go
server/internal/infrastructure/db/badger/round_repo.go
server/internal/infrastructure/db/service_test.go
server/internal/infrastructure/db/sqlite/round_repo.go
server/internal/infrastructure/ocean-wallet/account.go

This contains the following fixes:
- SQLite round repo: exclude rounds with empty connector address in `GetSweptRounds()`, align with what done in other impls
- Store the current round in memory to prevent sourcing it from the db in the several stages
- Thanks to the fix above, prevent storing aborted rounds (failed because empty)
- Prevent passing to ocean an empty connector address
All the bug fixed with this caused a round not to be finalized, @louisinger please review.
Testable version at https://asp.arkdev.info 
Closes #175.
Closes #194.

Fix errors on round finalization

---

pkg/client-sdk/ark_sdk.go
pkg/client-sdk/client.go
pkg/client-sdk/wallet/wallet_test.go
pkg/client-sdk/wasm/browser/exports.go
pkg/client-sdk/wasm/browser/wrappers.go

With this commit, the `pkg/client-sdk` now expose a IsLocked that maps to the wallet internal status
You can try with @bordalix 
```sh
go get -v github.com/ark-network/ark/pkg/client-sdk@50c9594da9d946a6a17118ac4734ca413bdaca55
```

pkg/client-sdk: expose IsLocked 

---

client/main.go
server/cmd/arkd/main.go

Now both `ark` and `arkd` can use a `--version` flag 
It closes #235

add flag --version

---

server/internal/infrastructure/wallet/btc-embedded/wallet.go

This PR contains small fixes regarding `admin/wallet` APIs panics (`wallet/balance` & `wallet/address` should return an error if the wallet is nil)
it closes #250 
@tiero please review

[server] fix unexpected panics when the wallet is not initialized

---

.github/workflows/ark.unit.yaml
pkg/client-sdk/go.mod
pkg/client-sdk/go.sum

`go work sync` runs `tidy` under the hood on each module. The current master doesnt has the last version. I have introduced a gh action to automatically check this during unit tests

check go work sync in unit test

---

server/internal/infrastructure/tx-builder/covenantless/builder.go

This PR fixes "missing input data" error in case the round tx has several inputs coming from the ASP wallet.
@tiero @bordalix please review

fix: AddInWitnessUtxo in covenantless `txBuilder`

---

client/main.go

This adds check to config cmd that prints message to user to run init cmd if config is not set, before this there was a panic if config store is empty.
This adds version flag support.
@tiero please review.

CLI - config cmd check & version flag

---

server/internal/core/application/covenant.go
server/internal/core/application/covenantless.go
server/internal/core/ports/tx_builder.go
server/internal/infrastructure/tx-builder/covenant/builder.go
server/internal/infrastructure/tx-builder/covenant/builder_test.go
server/internal/infrastructure/tx-builder/covenantless/builder.go
server/internal/infrastructure/tx-builder/covenantless/builder_test.go

This PR is a rework of the `createPoolTx` coin selection strategy. It fixes "dust" errors happening if the second fee estimation fails.

fix: `createPoolTx` coin selection

---

server/cmd/arkd/main.go
server/internal/app-config/config.go
server/internal/config/config.go
server/internal/core/ports/unlocker.go
server/internal/infrastructure/unlocker/file/service.go
server/internal/infrastructure/wallet/btc-embedded/wallet.go
server/internal/interface/grpc/service.go

This adds the auto unlocking feature.
The unlocker can be configured to source the password from anywhere, like for example an S3 bucket or a simple file. For now only a "file based" unlocker is available, but later we can add as many as we want.
For this, the server now has a new env vars `ARK_UNLOCKER_TYPE` to specify the unlocker type to use, and a `ARK_UNLOCKER_FILE_PATH` to specify the path of the file containing the password for the file based unlocker.
If the asp is not initialized, the auto unlock is simply skipped even if configured, the wallet must be unlocked manually after creation and the unlocking will work as expected from the next restart.
Closes #335.
Please @louisinger review.

Add auto-unlocker

---

server/cmd/arkd/main.go
server/internal/app-config/config.go
server/internal/config/config.go
server/internal/infrastructure/unlocker/env/service.go

This adds a new type of unlocker (`env`) that sources the password from env var `ARK_UNLOCKER_PASSWORD`.
Please @tiero  review.

Add env unlocker

---

client/main.go

This PR allows using the CLI with the REST client instead of gRPC
--rest optional flag will set arksdk.RestClient in init method.
```
ark init --rest .....
```

[CLI] add `--rest` optional flag `init` command

---

server/internal/core/application/covenant.go
server/internal/core/application/covenantless.go

Waiting time reduced: instead of `duration / 2`, registration phase waits `duration / 3`
Closes #312.

Change time allocation in round phases

---

server/internal/infrastructure/wallet/btc-embedded/wallet.go

This solves the error when unlocking the btc wallet connected via ZMQ to `bitcoind`.
Please @louisinger @tiero review.

Hotfix bct embedded wallet w/ ZMQ

---

server/internal/core/application/admin.go
server/internal/core/application/covenant.go
server/internal/core/application/covenantless.go
server/internal/core/application/sweeper.go
server/internal/core/domain/round_repo.go
server/internal/core/ports/tx_builder.go
server/internal/infrastructure/db/badger/round_repo.go
server/internal/infrastructure/db/sqlite/round_repo.go
server/internal/infrastructure/db/sqlite/sqlc/queries/query.sql.go
server/internal/infrastructure/db/sqlite/sqlc/query.sql
server/internal/infrastructure/tx-builder/covenant/builder.go
server/internal/infrastructure/tx-builder/covenant/builder_test.go
server/internal/infrastructure/tx-builder/covenant/coinselection.go
server/internal/infrastructure/tx-builder/covenantless/builder.go
server/internal/infrastructure/tx-builder/covenantless/builder_test.go

These changes propose a lighter version of some round repo APIs. The problem with the existing APIs is that they return all rounds data but in the end, only specific fields are used at app level.
The query used in the sqlite db to implement such APIs can lead to memory spikes in case it's a very a large one.
The solution proposed here is to change the round APIs so that they return exactly what is needed by the app svc.
Please @louisinger @sekulicd review this.

[Server] Round repo light APIs

---

common/tree/script_test.go

Add test cases that go through supported script closures: multisigClosure, csvMultisigClosure, cltvMultisigClosure and conditionMultisig.
If testing/code convention or anything regarding my code can be improved, please let me know, it would be helpful since I am starting out with Golang.
This should solve https://github.com/ark-network/ark/issues/395 (plan-b-network assignment)

test(common): add more script-decode test cases

---

common/bitcointree/builder.go
common/bitcointree/musig2_test.go
common/bitcointree/validation.go
common/tree/builder.go
common/tree/script.go
common/tree/script_test.go
common/tree/validation.go
common/tree/vtxo.go
pkg/client-sdk/covenantless_client.go
pkg/client-sdk/redemption/covenant_redeem.go
pkg/client-sdk/redemption/covenantless_redeem.go
pkg/client-sdk/wallet/singlekey/bitcoin_wallet.go
pkg/client-sdk/wallet/singlekey/liquid_wallet.go
server/internal/core/application/covenantless.go
server/internal/infrastructure/tx-builder/covenant/builder.go
server/internal/infrastructure/tx-builder/covenant/sweep.go
server/internal/infrastructure/tx-builder/covenantless/builder.go
server/internal/infrastructure/tx-builder/covenantless/sweep.go
server/internal/infrastructure/wallet/liquid-standalone/transaction.go

This adds for a new kind of policy for the VTXO script in order to support csv delayed multisig with an extra condition that must evaluate to bool.
The new closure is extension of the existing one `CSVMultisig`.
Please @bordalix review.

[common] Support csv-delayed closure with extra condition

---

pkg/client-sdk/client/grpc/client.go

This makes the grpc client of the client SDK support server URLs with `http://` prefix just like it supports the `https://` one.
Please @tiero review.

[SDK] Make grpc client support `http://`-prefixed server url

---

client/main.go

For some reason, it doesn't compile on windows without converting to int explicitly

FIx client build on windows

---

.github/workflows/ark.autogen_client.yaml
pkg/client-sdk/Makefile

This adds a new github action to ensure the client generated from swagger is up-to-date.
NOTE: the action is triggered if api-spec/ contains changes, so it's not expected to be executed by this pr. 
Closes #315 
Please @louisinger @sekulicd review

Add action to check REST client built from swagger

---

server/internal/core/application/sweeper.go
server/internal/core/domain/round_repo.go
server/internal/infrastructure/db/badger/round_repo.go
server/internal/infrastructure/db/service_test.go
server/internal/infrastructure/db/sqlite/round_repo.go
server/internal/infrastructure/db/sqlite/sqlc/queries/query.sql.go
server/internal/infrastructure/db/sqlite/sqlc/query.sql

This PR adds a more granular method `GetVtxoTreeWithTxid` in Round repository. It aims to reduce the sweeper starting time. 

add `RoundRepository.GetVtxoTreeWithTxid` method

---

go.work.sum
server/cmd/arkd/commands.go
server/cmd/arkd/main.go

The provided code changes introduce several modifications to the `arkd` command-line interface, primarily focusing on refactoring and improving the handling of flags and paths for macaroons and TLS certificates. Here's a summary of the key changes:
1. **Flag Refactoring**:
- Flag names have been moved to constants for better maintainability and readability. For example, `"url"` is now `flagURL`, and `"password"` is now `flagPassword`.
- This change ensures that flag names are consistently used throughout the code and makes it easier to modify them if needed in the future.
2. **New Function for Credential Paths**:
- A new function `getCredentialPaths(ctx *cli.Context)` is introduced. This function centralizes the logic for determining the paths of macaroons and TLS certificates.
- It …

arkd cli flags update

---

Dockerfile
server/cmd/arkd/main.go
server/internal/app-config/config.go
server/internal/config/config.go
server/internal/infrastructure/db/service.go
server/internal/infrastructure/db/service_test.go

With this, the migration files for server's sqlite db are embedded so that the env var ARK_DB_MIGRATION_PATH can be dropped.
Please @louisinger @sekulicd review

[Server] Embed migrations & Drop related env var

---

client/main.go
pkg/client-sdk/ark_sdk.go
pkg/client-sdk/covenant_client.go
pkg/client-sdk/covenantless_client.go
pkg/client-sdk/example/covenant/alice_to_bob.go
pkg/client-sdk/example/covenantless/alice_to_bob.go
pkg/client-sdk/wasm/browser/wrappers.go
server/Makefile
server/cmd/arkd/main.go
server/internal/app-config/config.go
server/internal/config/config.go
server/internal/core/application/covenantless.go
server/test/e2e/covenant/e2e_test.go
server/test/e2e/covenantless/e2e_test.go

This PR adds an `ALLOW_ZERO_FEES` flag for redeem transactions. It allows to submit redeem psbt with a zero fee value. It must be removed when we migrate to transaction V3 (https://github.com/ark-network/ark/pull/328). It's not ideal cause it makes the transaction not being relayed by full node from the onchain point of view, thus it's not possible to unilateral exit a zero-fee pending VTXO. 
It also adds a `withZeroFee` flag to covenantless `SendOffchain` method. It prevents the transaction builder to deduct min-relay-fee amount from the last output.
@tiero @bordalix @altafan please review

add `ALLOW_ZERO_FEES` flag

---

nak.Dockerfile
pkg/client-sdk/covenantless_client.go
pkg/client-sdk/test/wasm/wasm_test.go
pkg/client-sdk/wasm/browser/wrappers.go

_This PR adds a way to inspect the settlement process by replaying the`RoundEvent` received from the server to a custom channel created by the client. It also allow to do the same with JS using a callback function._
**Golang**
```go
eventsCh := make(chan client.RoundEvent)
defer close(eventsCh)
go func() {
for event := range eventsCh {
fmt.Println(event)
}
}()
resp, err := arkSdkClient.Settle(context.Background(), arksdk.WithEventsCh(eventsCh))
if err != nil {
return nil, err
}
```
**WASM JS wrapper**
```js
await settle((e) => console.log(JSON.parse(e)));
```
@tiero @bordalix @altafan @sekulicd  please review

[SDK] add `WithEventsCh` settle option

---

pkg/client-sdk/client/rest/client.go
server/internal/interface/grpc/handlers/arkservice.go
server/internal/interface/grpc/service.go

This makes the rest client of the client SDK properly handle the close of the event stream so that clients don't left connections opened unintentionally.
BONUS: This also makes the server able to force the close of such connections in case of shutdown.
Please @louisinger @bordalix @sekulicd review.

[SDK] Fix closing event stream in rest client

---

server/internal/core/application/covenant.go
server/internal/core/application/covenantless.go
server/internal/core/ports/tx_builder.go
server/internal/infrastructure/tx-builder/covenant/builder.go
server/internal/infrastructure/tx-builder/covenantless/builder.go
server/internal/infrastructure/wallet/btc-embedded/wallet.go

The purpose of this is to optimize the flow of finalizing a round. In particular:
- Embedded bitcoin wallet: cache forfeit address at creation/unlocking instead of doing so the very first time the relative API is called. Contains also some renaming for consistency.
- SubmitForfeitTxs API: move validation of txs signatures at round finalization to prevent clients to have wait for their calls to succeed (if a lot of clients join the same round)
Please @louisinger @sekulicd review.

[Server] Optmization of embedded wallet and forfeit tx validation

---

pkg/client-sdk/covenantless_client.go

This fixes the status of a pending tx: as soon as the vtxo has been spent the tx becomes settled.
Please @bordalix review

[SDK] Fix settled status for spent vtxos

---

server/internal/core/application/sweeper.go
server/internal/core/ports/tx_builder.go
server/internal/core/ports/wallet.go
server/internal/infrastructure/tx-builder/covenant/builder.go
server/internal/infrastructure/tx-builder/covenantless/builder.go

This PR adds a check in sweeper.go verifying that the tx is not already onchain before trying to broadcast it.

sweeper: check if tx is onchain before broadcasting

---

pkg/client-sdk/client/grpc/client.go
server/internal/core/application/covenant.go
server/internal/core/application/covenantless.go
server/internal/core/application/utils.go
server/test/e2e/covenantless/e2e_test.go
server/test/e2e/test_utils.go

This is attempt to improve on forfeits sync, before this after nonces & sigs were collected round would wait “third of remaining” and if forfeits were not sent after that time round would fail, with this round possibly extends this period, especially if gathering of nonces and sigs are fast, by waiting till round remaining time, it also saves time by lowering registration phase(currently in master roundInterval=60s, meaning reg phase were 20s in this phase where we testing we dont need more than few seconds i think).
```
roundRemainingDuration := time.Duration((s.roundInterval/3)*2-1) * time.Second
thirdOfRemainingDuration := time.Duration(roundRemainingDuration / 3)
```
@altafan please review.

Wait for forfeits until round ends

---

pkg/client-sdk/covenantless_client.go
server/internal/core/application/covenantless.go

_This PR fixes collaborative exit payment where there is no change (exit all)._
it includes 2 different fixes:
* server : handle `nil` musig2data.
* client : if onchain outputs only, skip musig2 signing steps.

handle collaborative exit without vtxo change

---

server/internal/core/application/utils.go

This PR cleans the requests map from outdated request. A request is outdated if the user didn't ping for at least 1 minute. It prevents `duplicated input` errors in case the client stops pinging and then retry with the same inputs.

[application] delete outdated tx requests

---

pkg/client-sdk/ark_sdk.go
pkg/client-sdk/client.go
pkg/client-sdk/covenantless_client.go
pkg/client-sdk/example/covenantless/alice_to_bob.go
pkg/client-sdk/store/kv/transaction_repository.go
pkg/client-sdk/store/kv/vtxo_repository.go
pkg/client-sdk/store/service_test.go
pkg/client-sdk/types/interfaces.go
pkg/client-sdk/types/types.go

This adds a new GetVtxoEventChannel API to the sdk client so that consumers can get notified whenever a list of vtxos is either added to the vtxo set or updated to spent.
This also adds changes so that GetTransactionEventChannel returns events for transactions that are added to the history, or updated to confirmed (onchain txs) or settled (offchain txs).
Please @bordalix @louisinger review this.

[SDK] Add GetVtxoEventChannel API

---

server/internal/core/application/covenantless.go

This PR fixes the way we handle the `forfeitsBoardingSigsChan` to avoid race condition and unexpected behavior. 
it closes #488 
@altafan @sekulicd please review

fix `forfeitsBoardingSigsChan` synchronization

---

server/go.mod
server/internal/interface/grpc/otel.go
server/internal/interface/grpc/service.go

This adds another ‘telemetry’ layer that will help us have better observability of arkd process it self.
We already have next metrics/dashboards: hostmetrics which gathers metrics for whole machine(cpu, RAM/Disc memory, Network/Disc I/O), we have arkd GPRC latency, count, request size, recently i added Cadvisor that tracks stats for each docker container running in machine separately and now I added metrics that will give us better insight into arkd go process it self. Check [here](https://github.com/sekulicd/ark/blob/7108217930ffe837cedf262d1fa3ad161747cc62/server/internal/interface/grpc/otel.go#L21) metrics i decided to track after investigation, goal is to inspect possible memory, go routines leaks, does gc behaves problematic, there is also metric tracking lock time for mutexes and …

Telemetry - Go runtime metrics

---

pkg/client-sdk/redemption/covenantless_redeem.go
server/pkg/kvdb/etcd/db.go
server/pkg/kvdb/etcd/readwrite_tx.go
server/pkg/macaroons/constraints_test.go
server/pkg/macaroons/service.go

make function comment match function name

chore: make function comment match function name

---

nak.Dockerfile
server/internal/core/application/covenant.go
server/internal/core/application/covenantless.go
server/internal/core/ports/tx_builder.go
server/internal/infrastructure/tx-builder/covenant/builder.go
server/internal/infrastructure/tx-builder/covenantless/builder.go

This includes server-side optimization for the execution of the round:
- Do not wait for the execution timeout to expire when a round doesn't contain boarding inputs or forfeit txs to be signed: this is a very edge case in which a round includes only users that are redeeming notes. In this case, users just need to sign the VTXO tree to complete the round execution. Before this, in such case, the server would have waited for the timeout to expire because clients wouldn't submit any signed boarding input or forfeit tx.
- Add safe checks to [`SignRoundTx`](https://github.com/ark-network/ark/blob/master/server/internal/core/application/covenantless.go#L776) to prevent overriding a round tx if the user didn't submit any signed boarding input. Before this, a malicious client could have …

Skip waiting for signed boarding ins/forfeit txs if none is required

---

common/bitcointree/pending.go
common/bitcointree/psbt.go
common/bitcointree/psbt_test.go
common/tree/vtxo.go
common/types.go
pkg/client-sdk/covenantless_client.go
server/internal/core/application/covenantless.go
server/internal/infrastructure/tx-builder/covenant/builder.go
server/test/e2e/covenantless/e2e_test.go

_This PR add robust checks on `SubmitRedeemTx` and `RegisterInputsForNextRound` RPCs. The idea is to validate the revealed tapscripts of every spent VTXO in order to prevent a malicious user to inject a "backdoor" tapscript._
The current `RegisterInputsForNextRoundRequest` has `Tapscripts` field on inputs. This PR only validates the scripts.
This PR introduces a **breaking change** for client, because now redeem PSBTs must reveal the inputs tapscripts using an unknown PSBT field "tapscripts".
_Why unknown field instead of TaprootLeafScript PSBT field ?_
We are using this field to signal the leaf used to sign, like most wallets do. Revealing the taproot tree using this field implies a lot of change on critical signing code (both clients and servers). Unknown field seems more adapted …

VtxoScript validation when spending a vtxo

---

pkg/client-sdk/client.go
pkg/client-sdk/client/client.go
pkg/client-sdk/client/grpc/client.go
pkg/client-sdk/client/rest/client.go
pkg/client-sdk/store/file/config_store.go
pkg/client-sdk/store/file/types.go
pkg/client-sdk/types/types.go

In order for clients to calculate the best market hour for future claims, its helpful to know when the server is expecting to run a happy hour. The server already gives that info on /v1/info. This PR makes that information visible in the SDK.

show market hour on sdk config

---

server/internal/core/application/covenantless.go

We decode twice the PSBT. This PR removes the unused `redeemTx` one.

SubmitRedeemTx: remove useless extra PSBT decode

---

common/bitcointree/vtxo.go
common/tree/vtxo.go

Add a check on `ParseVtxoScript` argument to prevent SubmitRedeemTx to panic in case a redeem tx does not reveal input's tapscripts.
Related to https://github.com/ark-network/ark/pull/505

hotfix: TapscriptsVtxoScript.Decode returns an error in case array is empty

---

common/bitcointree/psbt.go

We need `bytes.Contains` check to be compatible with Javascript libs. 

hotfix: `GetTaprootTree` use bytes.Contains instead of bytes.Equal

---

pkg/client-sdk/client.go
pkg/client-sdk/client/client.go
pkg/client-sdk/client/grpc/client.go
pkg/client-sdk/client/rest/client.go

This pr fixes the close of the server-side streams in both rest and grpc client used by the SDK.
This also cleans the `NotifyIncomingFunds` API as there was no need for wait groups.
@louisinger please review.

[SDK] Fix closing server-side streams & Polish NotifyIncomingFunds

---

pkg/client-sdk/client.go

This PR makes sure the wallet's `explorerURL` is set in case we are using default explorer URLs.

`pkg/client-sdk` store default explorer URL

---

server/internal/core/application/covenantless.go

The sweeper is responsible for watching and updating expiration timestamps. However, with the new SubscribeForAddress stream, it happens that the `ExpireAt` member is not updated when the notification hits the client. This PR fixes.
@altafan please reveiw

add `ExpireAt` member when adding new vtxos created by settlement

---

pkg/client-sdk/covenantless_client.go

This pr adds retry logic to the settlement flow of the SDK client. The max number of retries is hardcoded to 3, and if reached, the  the error of the last attempt is returned.
Please @tiero review

[SDK] Retry settlement

---

pkg/client-sdk/client.go

This fixes the `CompleteUnilateralExit` api of the client SDK by broadcasting the tx instead of just returning the base64 (psbt).
Please @tiero review

[SDK]: Broadcast tx when complete unilateral exit

---

server/internal/core/application/service.go
server/internal/core/application/service_event.go
server/internal/core/domain/events_repo.go
server/internal/core/domain/offchain_tx.go
server/internal/core/domain/offchain_tx_event.go
server/internal/core/domain/offchain_tx_test.go
server/internal/core/domain/round.go
server/internal/core/domain/round_event.go
server/internal/core/domain/round_test.go
server/internal/infrastructure/db/badger/utils.go
server/internal/infrastructure/db/service_test.go

This PR adds a `Type` member to events in order to make the parser to not rely on fields.

add domain.EventType

---

common/utils.go
docker-compose.regtest.yml
pkg/client-sdk/client.go
server/internal/config/config.go
server/internal/core/application/service.go
server/internal/infrastructure/db/service.go
server/test/e2e/e2e_test.go

This PR is handling sub-dust vtxo so that the server can treat them as expired VTXOs.
Sub-dust output are OP_RETURN output. These output types can be added to any offchain transactions. 
**sub-dust offchain tx output pkscript**
```
// unspendable "burn" output
OP_RETURN <x_only_tapkey>
```
Because they are OP_RETURN, they can't be spent again in another offchain tx. However, they can be registered in a settlement via BIP322 intent. To make the intent signature "standard" the `OP_RETURN` is replaced by `OP_1` : 
**sub-dust intent input pkscript**
```
// taproot output script
OP_1 <x_only_tapkey>
```
Thus, signing a subdust vtxo = signing a non-dust vtxo. 
The sub-dust VTXOs can't be exited unilaterally, so they do not require forfeit transactions.
it closes #479 
@altafan @Kukks please …

allow to send sub-dust amounts in offchain transactions

---

common/tree/script.go

DecodeClosure should handle uint8 absolute locktime.
@altafan @Kukks please review

Support uint8 CLTV locktime

---

server/internal/core/application/service.go
server/test/e2e/e2e_test.go

This bug is not on master. It makes every round without VTXOs outputs to fail because ComitmentTx is not set on current round.

startFinalization: Set CommitmentTx even if there is no vtxo tree
