arkade-os/arkd

README.md
=> Fix readme to use testnet for ark init

.github/workflows/ark.integration.yaml
=> trigger integration tests on PR

server/internal/infrastructure/ocean-wallet/account.go
=> [wallet] do not return locked connector utxo

client/covenant/init.go, client/covenantless/init.go, client/flags/flags.go, server/test/e2e/covenant/e2e_test.go, server/test/e2e/covenantless/e2e_test.go
This consolidate the flag name, with the internal variable name and in the documentation
=> client: rename flag ark-url into asp-url

docker-compose.clark.regtest.yml, docker-compose.regtest.yml, docker-compose.yml, go.work.sum, pkg/client-sdk/example/covenant/alice_to_bob.go, pkg/client-sdk/example/covenant/wasm/index.html, pkg/client-sdk/example/covenantless/alice_to_bob.go, pkg/client-sdk/example/covenantless/wasm/index.html, pkg/client-sdk/store/store_test.go, pkg/client-sdk/wallet/wallet_test.go, server/Makefile, server/internal/config/config.go, server/test/e2e/covenant/e2e_test.go, server/test/e2e/covenantless/e2e_test.go
- 6000 is used by chrome
- 6060 is used by Github Actions
7070 seems great
=> arkd: migrate to 7070 as default port

pkg/client-sdk/go.mod, pkg/client-sdk/go.sum
this fixes https://github.com/ark-network/ark/issues/260
=> client-sdk: bump api-spec and common to latest

pkg/client-sdk/ark_sdk.go, pkg/client-sdk/client.go
This allows users to list vtxos of their offchain wallet via the SDK
Please @bordalix @louisinger @sekulicd review this.
=> [SDK] Export ListVtxos

pkg/client-sdk/client/client.go, pkg/client-sdk/client/grpc/client.go, pkg/client-sdk/client/rest/client.go
Closes #284
Please @bordalix @sekulicd @louisinger review.
=> [SDK] Add SpentBy field to client.Vtxo

client/covenant/send.go, client/covenantless/send.go, pkg/client-sdk/internal/utils/utils.go, server/internal/core/application/covenantless.go
=> fix typo and spacing

.github/workflows/ark.unit.yaml, api-spec/go.mod, client/covenant/client.go, client/covenantless/client.go, server/pkg/kvdb/go.mod, server/pkg/macaroons/go.mod
Fix bug where `http://localhost:7070` for ASP url doesn't work but it should.
=> fix: support http as asp url

common/descriptor/expression.go, common/descriptor/parser.go, common/descriptor/parser_test.go
This PR fixes the descriptor parser, letting to parse bigger descriptors. It also adds a test with a 6-leaves descriptor.
=> fix descriptor parser to support multiple levels descriptors

pkg/client-sdk/client/rest/client.go, pkg/client-sdk/example/covenantless/wasm/README.md, pkg/client-sdk/example/covenantless/wasm/index.html, pkg/client-sdk/wasm/browser/exports.go, pkg/client-sdk/wasm/browser/wrappers.go, server/internal/core/application/covenant.go, server/internal/core/application/covenantless.go
This contains minor fixes to SDK's rest client and WASM wrappers.
Updates also the covenantless example in-browser.
Please @louisinger @bordalix review.
=> [SDK] Fix rest client and wasm

pkg/client-sdk/wasm/browser/exports.go, pkg/client-sdk/wasm/browser/wrappers.go
This PR changes WASM:
- changes LiquidReceivers to BitcoinReceivers
- adds sendAsync method to exports
- add dump method to exports
Tested.
@altafan @sekulicd please review
=> Add sendAsync to wasm

.github/workflows/ark.trivy.yaml
changes to the trivy gh action are taken from https://github.com/Enterprise-CMCS/mac-fc-github-actions-runner-aws/pull/227/files
=> Fix trivy gh action

server/internal/core/application/covenant.go, server/internal/core/application/covenantless.go
Server verifies the ASP public key of the address in ListVtxosRequest.
=> ListVtxos: validate address's server public key

pkg/client-sdk/ark_sdk.go, pkg/client-sdk/client.go, pkg/client-sdk/wasm/browser/exports.go, pkg/client-sdk/wasm/browser/wrappers.go
This PR adds a wrapper of `WalletService.SignTransaction` in client interface. 
=> [arksdk] add `ArkClient.SignTransaction`

.github/workflows/ark.unit.yaml, common/descriptor/parser_test.go
Add a `test-common` job in `ark.unit.yaml` 
@tiero please review
=> [CI] add common unit test workflow

client/main.go, common/network.go, pkg/client-sdk/client.go, pkg/client-sdk/internal/utils/utils.go, server/Makefile, server/internal/app-config/config.go, server/internal/config/config.go, server/internal/infrastructure/tx-builder/covenantless/builder.go, server/internal/infrastructure/wallet/btc-embedded/wallet.go
This adds support for any signet and adds commented TODOs for testnet4.
This closes issue #412
@altafan please review.
=> Support any signet

server/internal/interface/grpc/permissions/permissions.go, server/internal/interface/grpc/permissions/permissions_test.go
This fixes the macaroon permissions and related test after #421.
Please @louisinger @sekulicd review
=> Add explorer apis to macaroon whitelist

server/cmd/arkd/main.go
=> [Server] HotFix: add OTEL url to app config

server/internal/infrastructure/wallet/btc-embedded/wallet.go
`btc-embedded.GetForfeitAddress` queries the btcwallet DB, it leads to slow the `info` endpoint. This PR cache the result to speed up `GetForfeitAddress` calls.
@altafan @tiero please review
=> wallet/btc-embedded: cache `GetForfeitAddress` result

pkg/client-sdk/covenantless_client.go, pkg/client-sdk/types/types.go, pkg/client-sdk/wasm/browser/wrappers.go
This allows to show a "Destination" to Sent Transactions.
=> add spentby to tx

server/internal/infrastructure/db/sqlite/migration/20250207145917_add-index-on-round-txid.down.sql, server/internal/infrastructure/db/sqlite/migration/20250207145917_add-index-on-round-txid.up.sql
This adds an index to the txid field of the SQL round table db implementation to speed up such queries.
Please @louisinger @sekulicd review.
=> [SQL] Index round by txid

server/internal/core/application/covenant.go, server/internal/core/application/covenantless.go
=> [application] Reset the forfeit maps in `startRound`

pkg/client-sdk/ark_sdk.go, pkg/client-sdk/client.go, pkg/client-sdk/covenant_client.go, pkg/client-sdk/covenantless_client.go, pkg/client-sdk/example/covenantless/alice_to_bob.go, pkg/client-sdk/store/kv/transaction_repository.go, pkg/client-sdk/store/kv/vtxo_repository.go, pkg/client-sdk/store/service_test.go, pkg/client-sdk/types/interfaces.go, pkg/client-sdk/types/types.go, pkg/client-sdk/wasm/browser/wrappers.go
This updates the logic of the client sdk (only covenantless) for a correct recording of txs and vtxos while listening to the tx  stream.
Please @bordalix review.
=> [SDK] Update tx/vtxo management in tx feed

server/internal/infrastructure/db/badger/event_repo.go
Sometimes while running unit tests in CI, the event repo panics. This PR adds a waitGroup in the repo preventing`publishEvents` gorountines to panic.
=> [FIX] event_repo data race

server/internal/core/application/covenant.go, server/internal/core/application/covenantless.go, server/internal/core/application/utils.go
This adds waiting for boarding inputs signatures.
This closes #466
@altafan @louisinger please review.
=> Wait for boarding input signatures-v2

server/internal/config/config.go, server/internal/core/application/covenant.go, server/internal/core/application/covenantless.go, server/internal/core/application/types.go
This adds config for UTXO/VTXO limit amount.
It also adds config for max round participants.
This closes #480 
@altafan please review.
=> UTXO/VTXO limit config & Max round participants config

common/tree/script.go
=> hotfix: CLTV locktime decoding

pkg/client-sdk/client.go, pkg/client-sdk/covenant_client.go, pkg/client-sdk/covenantless_client.go
=> chore: fix some typos in comment

pkg/client-sdk/client.go
=> `pkg/wallet-sdk`: fix IsLocked

server/internal/interface/grpc/permissions/permissions.go, server/internal/interface/grpc/permissions/permissions_test.go
This fixes the macaroon permissions by adding the streams to the whitelist.
Fixes also the tests to ensure that also streams are included in the permission-ed/less list.
Please @tiero review.
=> [Server] Add streams to macaroon whitelist

server/internal/core/application/covenantless.go
This adds a check that makes a round fail early if the wallet balance doesn't cover the required amount for the batch.
Please @tiero review.
=> [Server] Make round failed if there's not enough liquidity

server/internal/core/application/covenantless.go
Related to https://github.com/ark-network/ark/pull/534
=> Return updated `spentVtxos` list in transactionEventsCh

server/internal/interface/grpc/handlers/arkservice.go
=> Fix collision in `SubscribeForAddress`

pkg/client-sdk/store/service_test.go
remove duplicate package imports
=> chore: remove duplicate package imports

docker-compose.regtest.yml, server/internal/config/config.go, server/internal/interface/grpc/otel.go, server/internal/interface/grpc/service.go
This adds ark_service_up metric that can/will be used by Alerting system to register that Ark is down.
@altafan please review.
=> Ark Up metric
